code --install-extension aaron-bond.better-comments
code --install-extension abusaidm.html-snippets
code --install-extension alefragnani.project-manager
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.jshint
code --install-extension dbaeumer.vscode-eslint
code --install-extension deerawan.vscode-faker
code --install-extension donjayamanne.githistory
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension eg2.vscode-npm-script
code --install-extension erichbehrens.pull-request-monitor
code --install-extension fabiospampinato.vscode-todo-plus
code --install-extension felixfbecker.php-intellisense
code --install-extension flowtype.flow-for-vscode
code --install-extension formulahendry.code-runner
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension humao.rest-client
code --install-extension jack89ita.open-file-from-path
code --install-extension kaiwood.center-editor-window
code --install-extension kisstkondoros.vscode-codemetrics
code --install-extension lamartire.git-indicators
code --install-extension lannonbr.vscode-js-annotations
code --install-extension lucax88x.codeacejumper
code --install-extension MattiasPernhult.vscode-todo
code --install-extension minhthai.vscode-todo-parser
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension Norin.fuzzy-search
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension PeterJausovec.vscode-docker
code --install-extension Pivotal.vscode-boot-dev-pack
code --install-extension Pivotal.vscode-manifest-yaml
code --install-extension Pivotal.vscode-spring-boot
code --install-extension PKief.material-icon-theme
code --install-extension pranaygp.vscode-css-peek
code --install-extension quicktype.quicktype
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension rubbersheep.gi
code --install-extension ryanluker.vscode-coverage-gutters
code --install-extension ryuta46.multi-command
code --install-extension sburg.vscode-javascript-booster
code --install-extension shardulm94.trailing-spaces
code --install-extension shengchen.vscode-checkstyle
code --install-extension shinnn.stylelint
code --install-extension siegebell.prettify-symbols-mode
code --install-extension silverbulleters.sonarqube-inject
code --install-extension sohibe.java-generate-setters-getters
code --install-extension vincaslt.highlight-matching-tag
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-initializr
code --install-extension WallabyJs.quokka-vscode
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension wwm.better-align
code --install-extension Zignd.html-css-class-completion
