/opt/vscode/bin/./code-insiders --install-extension aaron-bond.better-comments
/opt/vscode/bin/./code-insiders --install-extension abusaidm.html-snippets
/opt/vscode/bin/./code-insiders --install-extension alefragnani.project-manager
/opt/vscode/bin/./code-insiders --install-extension bmewburn.vscode-intelephense-client
/opt/vscode/bin/./code-insiders --install-extension christian-kohler.path-intellisense
/opt/vscode/bin/./code-insiders --install-extension CoenraadS.bracket-pair-colorizer-2
/opt/vscode/bin/./code-insiders --install-extension dbaeumer.jshint
/opt/vscode/bin/./code-insiders --install-extension dbaeumer.vscode-eslint
/opt/vscode/bin/./code-insiders --install-extension deerawan.vscode-faker
/opt/vscode/bin/./code-insiders --install-extension donjayamanne.githistory
/opt/vscode/bin/./code-insiders --install-extension dsznajder.es7-react-js-snippets
/opt/vscode/bin/./code-insiders --install-extension eamodio.gitlens
/opt/vscode/bin/./code-insiders --install-extension ecmel.vscode-html-css
/opt/vscode/bin/./code-insiders --install-extension eg2.vscode-npm-script
/opt/vscode/bin/./code-insiders --install-extension erichbehrens.pull-request-monitor
/opt/vscode/bin/./code-insiders --install-extension fabiospampinato.vscode-todo-plus
/opt/vscode/bin/./code-insiders --install-extension felixfbecker.php-intellisense
/opt/vscode/bin/./code-insiders --install-extension flowtype.flow-for-vscode
/opt/vscode/bin/./code-insiders --install-extension formulahendry.code-runner
/opt/vscode/bin/./code-insiders --install-extension Gruntfuggly.todo-tree
/opt/vscode/bin/./code-insiders --install-extension HookyQR.beautify
/opt/vscode/bin/./code-insiders --install-extension humao.rest-client
/opt/vscode/bin/./code-insiders --install-extension jack89ita.open-file-from-path
/opt/vscode/bin/./code-insiders --install-extension kaiwood.center-editor-window
/opt/vscode/bin/./code-insiders --install-extension kisstkondoros.vscode-codemetrics
/opt/vscode/bin/./code-insiders --install-extension lamartire.git-indicators
/opt/vscode/bin/./code-insiders --install-extension lannonbr.vscode-js-annotations
/opt/vscode/bin/./code-insiders --install-extension lucax88x.codeacejumper
/opt/vscode/bin/./code-insiders --install-extension MattiasPernhult.vscode-todo
/opt/vscode/bin/./code-insiders --install-extension minhthai.vscode-todo-parser
/opt/vscode/bin/./code-insiders --install-extension ms-vscode.vscode-typescript-tslint-plugin
/opt/vscode/bin/./code-insiders --install-extension msjsdiag.debugger-for-chrome
/opt/vscode/bin/./code-insiders --install-extension Norin.fuzzy-search
/opt/vscode/bin/./code-insiders --install-extension octref.vetur
/opt/vscode/bin/./code-insiders --install-extension oderwat.indent-rainbow
/opt/vscode/bin/./code-insiders --install-extension PeterJausovec.vscode-docker
/opt/vscode/bin/./code-insiders --install-extension Pivotal.vscode-boot-dev-pack
/opt/vscode/bin/./code-insiders --install-extension Pivotal.vscode-manifest-yaml
/opt/vscode/bin/./code-insiders --install-extension Pivotal.vscode-spring-boot
/opt/vscode/bin/./code-insiders --install-extension PKief.material-icon-theme
/opt/vscode/bin/./code-insiders --install-extension pranaygp.vscode-css-peek
/opt/vscode/bin/./code-insiders --install-extension quicktype.quicktype
/opt/vscode/bin/./code-insiders --install-extension redhat.java
/opt/vscode/bin/./code-insiders --install-extension redhat.vscode-yaml
/opt/vscode/bin/./code-insiders --install-extension rubbersheep.gi
/opt/vscode/bin/./code-insiders --install-extension ryanluker.vscode-coverage-gutters
/opt/vscode/bin/./code-insiders --install-extension ryuta46.multi-command
/opt/vscode/bin/./code-insiders --install-extension sburg.vscode-javascript-booster
/opt/vscode/bin/./code-insiders --install-extension shardulm94.trailing-spaces
/opt/vscode/bin/./code-insiders --install-extension shengchen.vscode-checkstyle
/opt/vscode/bin/./code-insiders --install-extension shinnn.stylelint
/opt/vscode/bin/./code-insiders --install-extension siegebell.prettify-symbols-mode
/opt/vscode/bin/./code-insiders --install-extension silverbulleters.sonarqube-inject
/opt/vscode/bin/./code-insiders --install-extension sohibe.java-generate-setters-getters
/opt/vscode/bin/./code-insiders --install-extension vincaslt.highlight-matching-tag
/opt/vscode/bin/./code-insiders --install-extension VisualStudioExptTeam.vscodeintellicode
/opt/vscode/bin/./code-insiders --install-extension vscjava.vscode-java-debug
/opt/vscode/bin/./code-insiders --install-extension vscjava.vscode-java-dependency
/opt/vscode/bin/./code-insiders --install-extension vscjava.vscode-java-pack
/opt/vscode/bin/./code-insiders --install-extension vscjava.vscode-java-test
/opt/vscode/bin/./code-insiders --install-extension vscjava.vscode-maven
/opt/vscode/bin/./code-insiders --install-extension vscjava.vscode-spring-initializr
/opt/vscode/bin/./code-insiders --install-extension WallabyJs.quokka-vscode
/opt/vscode/bin/./code-insiders --install-extension wayou.vscode-todo-highlight
/opt/vscode/bin/./code-insiders --install-extension wix.vscode-import-cost
/opt/vscode/bin/./code-insiders --install-extension wwm.better-align
/opt/vscode/bin/./code-insiders --install-extension Zignd.html-css-class-completion
